columnSuffix: null
handle: siteIntroduction
instructions: null
name: 'Site Introduction'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: e00e1efa-bb86-4ee8-b669-4a726b8a5427 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
