# Do not edit this file, it’s used by GitHub Actions.
CRAFT_DB_DRIVER=pgsql
CRAFT_DB_SERVER=postgres
CRAFT_DB_DATABASE=test
CRAFT_DB_USER=postgres
CRAFT_DB_PASSWORD=postgres
CRAFT_DB_SCHEMA=public
CRAFT_SECURITY_KEY=12345
